---
# tasks file for python
- name: Install Python dependencies
  yum: 
    name: {{ item }} 
    state: present
  with_items:
      - python3
      - python3-pip
      - python-setuptools
      - python-dev